### ISSUE TITLE
ENH: /en/gh-pages[-rev]/, / -> /en/latest/

### ISSUE THREAD

**Issue by westurner** [westurner/pgs#4]
e.g. 

```
/gh-pages/
/v0.1.0/
/gh-pages-v0.1.0/
```

and then optional language code passthrough

```
/en/gh-pages/
/en/latest/
```
### tasks
- [ ] redirect URLS: 300 multiple choices, 302 found, 307 temporary redirect
- [ ] rewrite URLS: it's often much easier to serve from `//` (than to rewrite paths)

**Comment by westurner** [comment]
- sticky revisions (e.g. session cookie, localstorage, populated dropdown selector)

**Comment by westurner** [comment]
> sticky revisions (e.g. session cookie, localstorage, populated dropdown selector)
- to make e.g. `/images/img.PNG` -> `/en/latest/images/img.PNG`

```
/images/img.PNG
/en/latest/images/img.PNG
/en/v0.1.0/images/img.PNG
/en/gh-pages/images/img.PNG
```
- [ ] cache / redirect appropriately

..
- [ ] append js bar/button/hover overlay?

**Comment by westurner** [comment]
```
/en/latest/ -> ./<-p /root_path/>
/en/latest/ -> /<-g /git_repo_path/>
/[lang]/[revision] ->  [
#   {"xml:lang": "en-US", "path": "./reponame/[.git]"},
#   {"xml:lang": "en-US", "path": "./reponame/en-US/[.git]"},
    {"xml:lang": "en-GB", "path": "./reponame/en-GB/[.git]"}, "
 ]  
```

...

```

{ [...], "url[_path/route]": ["en", "/en-US"] }
```

**Comment by westurner** [comment]
```
/en/latest/ -> ./<-p /root_path/>
/en/latest/ -> /<-g /git_repo_path/>
/[lang]/[revision] ->  [
#   {"xml:lang": "en-US", "path": "./reponame/[.git]"},
#   {"xml:lang": "en-US", "path": "./reponame/[.git:gh-pages/en-US]"},
    {"xml:lang": "en-GB", "path": "./reponame/[.git:gh-pages/en-GB]"}, 
 ]  
```

**Comment by westurner** [comment]
```
/en/latest/ -> ./<-p /root_path/>
/en/latest/ -> /<-g /git_repo_path/>
/[lang]/[revision] ->  [
#   {"xml:lang": "en-US", "path": "./reponame/[.git:gh-pages]/"},
#   {"xml:lang": "en-US", "path": "./reponame/[.git:gh-pages]/en-US"},
    {"xml:lang": "en-GB", "path": "./reponame/[.git:gh-pages]/en-GB"}, 
 ]  
```
